name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t img1:latest .


    - name: Tag to dockerhub
      run: docker tag img1:latest vaishnavi0601/node-docker:commit
    - name: Push to dockerhub

      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: vaishnavi0601/node-docker:commit1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}      
 
